### ISSUE TITLE
npm run build 出现了 这个报错

### ISSUE THREAD

**Issue by Lisi13613787118** [Chris-wei/vue-clip#2]
ERROR in static/js/app.027913c9b76df73513c4.js from UglifyJs
Unexpected token: punc (() [./static/clipper.js:13,0][static/js/app.027913c9b76df73513c4.js:70,9]

**Comment by Chris-wei** [comment]
安装 babel-preset-es2015 ， 检查一下babel配置试试

**Comment by Lisi13613787118** [comment]
谢谢 已解决
