### ISSUE TITLE
选择完图片之后报这个错误

### ISSUE THREAD

**Issue by shuaiyafei** [Chris-wei/vue-clip#3]
cropper.js:3255 GET http://localhost:20121/user/originUrl 404 (Not Found)

**Comment by Chris-wei** [comment]
npm install cropperjs --save  后试试

**Comment by shuaiyafei** [comment]
![Uploading image.png…]()

是不是我单独拿出来封成一个组件的问题

**Comment by Chris-wei** [comment]
嗯，可以试试，这个问题我暂时没想到，原谅我小白一枚 T_T

**Comment by shuaiyafei** [comment]
= = 我再看看吧
